apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: gemini-sandbox
  namespace: hackathon-judge
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: gemini-sandbox
    spec:
      serviceAccountName: hackathon-judge-sandbox-sa
      runtimeClassName: gvisor
      containers:
        - name: gemini-sandbox
          image: "${ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/${ARTIFACT_REPO_NAME}/agent-sandbox:$COMMIT_SHA"
          securityContext:
            allowPrivilegeEscalation: false
          ports:
          - containerPort: 8888
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
          env:
          - name: GOOGLE_CLOUD_PROJECT
            value: $GOOGLE_CLOUD_PROJECT
          - name: GOOGLE_CLOUD_LOCATION
            value: "global"
          - name: GOOGLE_GENAI_USE_VERTEXAI
            value: "true"
          - name: SANDBOX_DIR
            value: "/home/sandbox/app"