apiVersion: v1
kind: ConfigMap
metadata:
  name: hackathon-judge-config
  namespace: hackathon-judge
data:
  GOOGLE_CLOUD_PROJECT: "${GOOGLE_CLOUD_PROJECT}"
  GOOGLE_CLOUD_REGION: "${GOOGLE_CLOUD_REGION}"
  TASKS_TOPIC: "${TASKS_TOPIC}"
  RESULTS_TOPIC: "${RESULTS_TOPIC}"
  TASKS_SUBSCRIPTION: "${TASKS_SUBSCRIPTION}"
  RESULTS_SUB: "${RESULTS_SUB}"
