apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hackathon-judge-route
  namespace: hackathon-judge
spec:
  parentRefs:
  - name: hackathon-judge-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: backend
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend
      port: 80
