apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sandbox-router-gateway
  namespace: hackathon-judge
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
        - kind: HTTPRoute
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sandbox-router-route
  namespace: hackathon-judge
spec:
  parentRefs:
  - name: sandbox-router-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: sandbox-router-svc
      port: 8080
---
# HealthCheckPolicy tells the GKE Gateway to use the router app "/healthz" endpoint for its health
# checks instead of the default "/".
apiVersion: networking.gke.io/v1 # Specific to GKE
kind: HealthCheckPolicy
metadata:
  name: router-health-check-policy
  namespace: hackathon-judge
spec:
  targetRef:
    group: ""
    kind: Service
    name: sandbox-router-svc # This must match the name of the router's service
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /healthz # Tell the health checker to use this path
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: router-backend-policy
  namespace: hackathon-judge
spec:
  default:
    timeoutSec: 600 # 10 minutes (change to whatever max execution time they need)
  targetRef:
    group: ""
    kind: Service
    name: sandbox-router-svc
