apiVersion: v1
kind: ServiceAccount
metadata:
  name: hackathon-judge-sa
  namespace: hackathon-judge
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hackathon-judge-sandbox-sa
  namespace: hackathon-judge
